"""initial

Revision ID: f6ecc722a4d1
Revises: 
Create Date: 2026-09-03 22:34:28.982207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ecc722a4d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('architectures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('aws', 'gcp', 'azure')", name='ck_architecture_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architectures_user_id'), 'architectures', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('architecture_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('application_component', 'vpc')", name='ck_collection_type'),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_architecture_id'), 'collections', ['architecture_id'], unique=False)
    op.create_table('data_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('architecture_id', sa.UUID(), nullable=False),
    sa.Column('from_collection_id', sa.UUID(), nullable=False),
    sa.Column('to_collection_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_collection_id != to_collection_id', name='ck_connector_no_self_link'),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ),
    sa.ForeignKeyConstraint(['from_collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['to_collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_connectors_architecture_id'), 'data_connectors', ['architecture_id'], unique=False)
    op.create_table('sku_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('service_code', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('pricing_term', sa.String(length=20), nullable=False),
    sa.Column('purchase_option', sa.String(length=20), nullable=False),
    sa.Column('usage_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pricing_term IN ('on_demand', 'reserved_1yr', 'reserved_3yr')", name='ck_sku_selection_pricing_term'),
    sa.CheckConstraint("purchase_option IN ('no_upfront', 'partial_upfront', 'all_upfront', 'not_applicable')", name='ck_sku_selection_purchase_option'),
    sa.CheckConstraint('(collection_id IS NOT NULL)::int + (connector_id IS NOT NULL)::int = 1', name='ck_sku_selection_exactly_one_parent'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['connector_id'], ['data_connectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_selections_collection_id'), 'sku_selections', ['collection_id'], unique=False)
    op.create_index(op.f('ix_sku_selections_connector_id'), 'sku_selections', ['connector_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sku_selections_connector_id'), table_name='sku_selections')
    op.drop_index(op.f('ix_sku_selections_collection_id'), table_name='sku_selections')
    op.drop_table('sku_selections')
    op.drop_index(op.f('ix_data_connectors_architecture_id'), table_name='data_connectors')
    op.drop_table('data_connectors')
    op.drop_index(op.f('ix_collections_architecture_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_architectures_user_id'), table_name='architectures')
    op.drop_table('architectures')
    op.drop_table('users')
    # ### end Alembic commands ###
