"""collection nesting

Revision ID: 0cfcc0d58f3f
Revises: f6ecc722a4d1
Create Date: 2026-09-08 11:26:08.932840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfcc0d58f3f'
down_revision: Union[str, Sequence[str], None] = 'f6ecc722a4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('parent_collection_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_collections_parent_collection_id'), 'collections', ['parent_collection_id'], unique=False)
    op.create_foreign_key(
        'fk_collections_parent_collection_id',
        'collections', 'collections', ['parent_collection_id'], ['id'], ondelete='SET NULL',
    )
    op.create_check_constraint('ck_collection_no_self_parent', 'collections', 'parent_collection_id != id')
    op.create_check_constraint('ck_collection_parent_only_app_component', 'collections', "parent_collection_id IS NULL OR type = 'application_component'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_collection_parent_only_app_component', 'collections', type_='check')
    op.drop_constraint('ck_collection_no_self_parent', 'collections', type_='check')
    op.drop_constraint('fk_collections_parent_collection_id', 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_parent_collection_id'), table_name='collections')
    op.drop_column('collections', 'parent_collection_id')
    # ### end Alembic commands ###
