"""standard architectures

Revision ID: 7c2e9d41b8a3
Revises: db1df84f4a73
Create Date: 2026-09-25 12:00:00.000000

Seeds the four standard architectures (014-architecture-templates-import-export, spec
FR-001-FR-007, research.md §1-§2) under the default Admin account, public, from the checked-in
`src/db/seed/standard_architectures.json` (generated by `scripts/resolve_standard_architectures.py`
— never hand-edited). An Alembic revision runs exactly once per database, which is what makes
the standard architectures "created once, never recreated" (spec FR-003) without any marker
table: an Admin who later deletes or renames one keeps that choice.

Plain SQL only, in the style of `0004` — this migration never imports the app ORM, so later
model changes can't break it — and it needs no pricing data at run time (the seed already holds
resolved `service_code`/`sku` references, never prices).
"""
import json
import uuid
from decimal import Decimal
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2e9d41b8a3'
down_revision: Union[str, Sequence[str], None] = 'db1df84f4a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SEED_PATH = Path(__file__).resolve().parents[2] / "seed" / "standard_architectures.json"


def _seed() -> dict:
    return json.loads(SEED_PATH.read_text())


def insert_standard_architectures(connection) -> None:
    """Insert every seeded architecture the Admin doesn't already own (by name, among
    non-deleted architectures) — a defensive guard; in normal operation this runs once.

    `clock_timestamp()` (not `now()`, which is fixed for the whole transaction) gives each row a
    distinct, increasing `created_at`, because collections and SKU selections are displayed in
    `created_at` order (orm.py) — so the seeded services keep the seed's order.
    """
    admin_id = connection.execute(
        sa.text("SELECT id FROM users WHERE is_default_admin LIMIT 1")
    ).scalar_one_or_none()
    if admin_id is None:
        return

    for architecture in _seed()["architectures"]:
        exists = connection.execute(
            sa.text(
                "SELECT 1 FROM architectures "
                "WHERE user_id = :owner AND name = :name AND deleted_at IS NULL"
            ).bindparams(owner=admin_id, name=architecture["name"])
        ).first()
        if exists is not None:
            continue

        architecture_id = uuid.uuid4()
        connection.execute(
            sa.text(
                "INSERT INTO architectures (id, user_id, provider, name, is_public, created_at, "
                "updated_at) VALUES (:id, :owner, :provider, :name, true, clock_timestamp(), "
                "clock_timestamp())"
            ).bindparams(
                id=architecture_id,
                owner=admin_id,
                provider=architecture["provider"],
                name=architecture["name"],
            )
        )

        # The seed holds only VPC collections (no nesting, no connectors — spec FR-007), but the
        # ref map keeps this correct for any parent-before-child ordering.
        ref_to_id: dict[str, uuid.UUID] = {}
        for collection in architecture["collections"]:
            collection_id = uuid.uuid4()
            ref_to_id[collection["ref"]] = collection_id
            connection.execute(
                sa.text(
                    "INSERT INTO collections (id, architecture_id, type, name, region, "
                    "parent_collection_id, created_at, updated_at) VALUES (:id, :architecture, "
                    ":type, :name, :region, :parent, clock_timestamp(), clock_timestamp())"
                ).bindparams(
                    id=collection_id,
                    architecture=architecture_id,
                    type=collection["type"],
                    name=collection["name"],
                    region=collection["region"],
                    parent=ref_to_id.get(collection["parent_ref"]),
                )
            )
            for selection in collection["sku_selections"]:
                connection.execute(
                    sa.text(
                        "INSERT INTO sku_selections (id, collection_id, service_code, sku, "
                        "pricing_term, purchase_option, usage_quantity, created_at, updated_at) "
                        "VALUES (:id, :collection, :service_code, :sku, :pricing_term, "
                        ":purchase_option, :usage_quantity, clock_timestamp(), clock_timestamp())"
                    ).bindparams(
                        id=uuid.uuid4(),
                        collection=collection_id,
                        service_code=selection["service_code"],
                        sku=selection["sku"],
                        pricing_term=selection["pricing_term"],
                        purchase_option=selection["purchase_option"],
                        # Serialized as a decimal string in the export format.
                        usage_quantity=Decimal(str(selection["usage_quantity"])),
                    )
                )


def upgrade() -> None:
    """Upgrade schema."""
    insert_standard_architectures(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    names = [a["name"] for a in _seed()["architectures"]]
    owned = (
        "SELECT a.id FROM architectures a JOIN users u ON u.id = a.user_id "
        "WHERE u.is_default_admin AND a.name = ANY(:names)"
    )
    params = {"names": names}
    op.execute(
        sa.text(
            "DELETE FROM sku_selections WHERE collection_id IN "
            f"(SELECT id FROM collections WHERE architecture_id IN ({owned}))"
        ).bindparams(**params)
    )
    op.execute(
        sa.text(f"DELETE FROM collections WHERE architecture_id IN ({owned})").bindparams(**params)
    )
    op.execute(sa.text(f"DELETE FROM architectures WHERE id IN ({owned})").bindparams(**params))
